<?php
/**
 * Created by PhpStorm.
 * User: humberto.galletto
 * Date: 28/10/2015
 * Time: 15:58
 */

error_reporting(E_ALL);
ini_set('display_errors', 'On');

require_once '../../../../autoload.php';

use NFePHP\NFe\DsNFe;

$dhEmi = str_replace(" ", "T", date("Y-m-d H:i:sP"));
$dhSaiEnt = str_replace(" ", "T", date("Y-m-d H:i:sP"));
$tempData = explode("-", $dhEmi);

$nfeDados = array(
    'NFe' => array(
        'cUF' => '35',                                                  //Código da UF do emitente do Documento Fiscal
        'cNF' => '00000009',                                            //Código Numérico que compõe a Chave de Acesso
        'natOp' => 'VENDA DE PRODUTO',                                  //Descrição da Natureza da Operação
        'indPag' => '1',                                                //Indicador da forma de pagamento
        'mod' => '55',                                                  //Código do Modelo do Documento Fiscal
        'serie' => '001',                                               //Série do Documento Fiscal
        'nNF' => '9',                                                   //Número do Documento Fiscal
        'dhEmi' => $dhEmi,                                              //Data e hora de emissão do Documento Fiscal
        'dhSaiEnt' => ($dhSaiEnt?$dhSaiEnt:''),                         //OPICIONAL - Data e hora de Saída ou da Entrada da Mercadoria/Produto
        'tpNF' => '1',                                                  //Tipo de Operação
        'idDest' => '2',                                                //Identificador de local de destino da operação
        'cMunFG' => '3550308',                                          //Código do Município de Ocorrência do Fato Gerador
        'tpImp' => '1',                                                 //Formato de Impressão do DANFE
        'tpEmis' => '1',                                                //Tipo de Emissão da NF-e
        'cDV' => '4',                                                   //Dígito Verificador da Chave de Acesso da NF-e
        'tpAmb' => '2',                                                 //Identificação do Ambiente
        'finNFe' => '1',                                                //Finalidade de emissão da NF-e
        'indFinal' => '0',                                              //Indica operação com Consumidor final
        'indPres' => '9',                                               //Indicador de presença do comprador no estabelecimento comercial no momento da operação
        'procEmi' => '0',                                               //Processo de emissão da NF-e
        'verProc' => '3.22.8',                                          //Versão do Processo de emissão da NF-e
        'dhCont' => '',                                                 //Data e Hora da entrada em contingência
        'xJust' => '',                                                  //Justificativa da entrada em contingência
        'ano' => $tempData[0] - 2000,                                   //campo não existente no manual, necessário apenas para NFePHP
        'mes' => $tempData[1],                                          //campo não existente no manual, necessário apenas para NFePHP
        'versao' => '3.10'),                                            //Versão do leiaute
    'Emitente' => array(
        'CNPJ' => '58716523000119',                                     //CNPJ do emitente
        'CPF' => '',                                                    //CPF do remetente
        'xNome' => 'FIMATEC TEXTIL LTDA',                               //Razão Social ou Nome do emitente
        'xFant' => 'FIMATEC',                                           //Nome fantasia
        'IE' => '112006603110',                                         //Inscrição Estadual do Emitente
        'IEST' => '',                                                   //IE do Substituto Tributário
        'IM' => '95095870',                                             //Inscrição Municipal do Prestador de Serviço
        'CNAE' => '0131380',                                            //CNAE fiscal
        'CRT' => '3',                                                   //Código de Regime Tributário
        'xLgr' => 'RUA DOS PATRIOTAS',                                  //Logradouro
        'nro' => '897',                                                 //Número
        'xCpl' => 'ARMAZEM 42',                                         //Complemento
        'xBairro' => 'IPIRANGA',                                        //Bairro
        'cMun' => '3550308',                                            //Código do município
        'xMun' => 'Sao Paulo',                                          //Nome do município
        'UF' => 'SP',                                                   //Sigla da UF
        'CEP' => '04207040',                                            //Código do CEP
        'cPais' => '1058',                                              //Código do País
        'xPais' => 'BRASIL',                                            //Nome do País
        'fone' => '1120677300'),                                        //Telefone
    'Destinatario' => array(
        'CNPJ' => '10702368000155',                                     //CNPJ do destinatário
        'CPF' => '',                                                    //CPF do destinatário
        'idEstrangeiro' => '',                                          //Identificação do destinatário no caso de comprador estrangeiro
        'xNome' => 'M R SANTOS DE PAULA TECIDOS ME',                    //Razão Social ou nome do destinatário
        'indIEDest' => '1',                                             //Indicador da IE do Destinatário
        'IE' => '244827055110',                                         //Inscrição Estadual do Destinatário
        'ISUF' => '',                                                   //Inscrição na SUFRAMA
        'IM' => '',                                                     //Inscrição Municipal do Tomador do Serviço
        'email' => 'linux.rlm@gmail.com',                               //Email
        'xLgr' => 'AV GASPAR RICARDO',                                  //Logradouro
        'nro' => '471',                                                 //Número
        'xCpl' => '',                                                   //Complemento
        'xBairro' => 'CENTRO',                                          //Bairro
        'cMun' => '4115200',                                            //Código do município
        'xMun' => 'Maringa',                                            //Nome do município
        'UF' => 'PR',                                                   //Sigla da UF
        'CEP' => '87040365',                                            //Código do CEP
        'cPais' => '1058',                                              //Código do País
        'xPais' => 'BRASIL',                                            //Nome do País
        'fone' => '4430330100'),                                        //Telefone
    'Retirada' => array(                                                //INFORMAR SOMENTE SE DIFERENTE DO ENDERECO DO REMETENTE
        'CNPJ' => '12345678901234',                                     //CNPJ
        'CPF' => '',                                                    //CPF
        'xLgr' => 'Rua Vanish',                                         //Logradouro
        'nro' => '000',                                                 //Número
        'xCpl' => 'Ghost',                                               //Complemento
        'xBairro' => 'Assombrado',                                      //Bairro
        'cMun' => '3509502',                                            //Código do município
        'xMun' => 'Campinas',                                           //Nome do município
        'UF' => 'SP'),                                                  //Sigla da UF
    'Entrega' => array(                                                 //Informar somente se diferente do endereço destinatário.
        'CNPJ' => '12345678901234',                                     //CNPJ
        'CPF' => '',                                                    //CPF
        'xLgr' => 'Viela Mixuruca',                                     //Logradouro
        'nro' => '2',                                                   //Número
        'xCpl' => 'Quabrada do malandro',                               //Complemento
        'xBairro' => 'Favela Mau Olhado',                               //Bairro
        'cMun' => '3509502',                                            //Código do município
        'xMun' => 'Campinas',                                           //Nome do município
        'UF' => 'SP'),                                                  //Sigla da UF
    'AutAcessoXML' => array(
        array(
            'CNPJ' => '',                                               //CNPJ Autorizado
            'CPF' => '')),                                              //CPF Autorizado
    'NfeRef' => array(                                                  //Grupo com informações de Documentos Fiscais referenciados. Informação utilizada nas hipóteses previstas na legislação. (Ex.: Devolução de mercadorias, Substituição de NF cancelada, Complementação de NF, etc.).
        'refNFe' => '',                                                 //Referencia uma NF-e (modelo 55) emitida anteriormente, vinculada a NF-e atual, ou uma NFC-e (modelo 65),
        'tipo'  => 0),                                                  //0 - mod 1A; 1 - Prod Rural; 2 - CT-e; 3 - Cupom fiscal
    'NfeRef1A' => array(                                                //Informação da NF modelo 1/1A referenciada
        'cUF' => '35',                                                  //Código da UF do emitente
        'AAMM' => '1312',                                               //Ano e Mês de emissão da NF-e
        'CNPJ' => '12345678901234',                                     //CNPJ do emitente
        'mod' => '1A',                                                  //Modelo do Documento Fiscal
        'serie' => '0',                                                 //Série do Documento Fiscal
        'nNF' => '1234'),                                               //Número do Documento Fiscal
    'NfeRefProdRural' => array(                                         //Informações da NF de produtor rural referenciada
        'cUF' => '35',                                                  //Código da UF do emitente
        'AAMM' => '1312',                                               //Ano e Mês de emissão da NF-e
        'CNPJ ' => '12345678901234',                                    //CNPJ do emitente
        'CPF' => '123456789',                                           //CPF do emitente
        'IE' => '123456',                                               //IE do emitente
        'mod' => '1',                                                   //Modelo do Documento Fiscal
        'serie' => '0',                                                 //Série do Documento Fiscal
        'nNF' => '1234'),                                               //Número do Documento Fiscal
    'CteRef' => array(
        'refCTe' => ''),                                                //Chave de acesso do CT-e referenciada
    'EcfRef' => array(                                                  //Informações do Cupom Fiscal referenciado
        'mod' => '90',                                                  //Modelo do Documento Fiscal
        'nECF' => '12243',                                              //Número de ordem sequencial do ECF
        'nCOO' => '111'),                                               //Número do Contador de Ordem de Operação - COO
    'det' => array(
        array(
        'nItem' => 1,
        'Produto' => array(
            'cProd' => '2517BCB01',                                     //Código do produto ou serviço
            'cEAN' => '97899072659522',                                 //GTIN (Global Trade Item Number) do produto, antigo código EAN ou código de barras
            'xProd' => 'DELFOS 80 MESCLA TINTO C/ AMAC. S.T 1,78M',     //Descrição do produto ou serviço
            'NCM' => '60063300',                                        //Código NCM com 8 dígitos
            'NVE' => array(
                array(
                'texto' => 'dfgh')),
            'EXTIPI' => '',                                             //EX_TIPI
            'CFOP' => '6101',                                           //Código Fiscal de Operações e Prestações
            'uCom' => 'KG',                                             //Unidade Comercial do produto
            'qCom' => '389.9500',                                       //Quantidade Comercial
            'vUnCom' => '49.9200000000',                                //Valor Unitário de Comercialização
            'vProd' => '19466.30',                                      //Valor Total Bruto dos Produtos ou Serviços
            'cEANTrib' => '',                                           //GTIN (Global Trade Item Number) da unidade tributável, antigo código EAN ou código de barras
            'uTrib' => 'KG',                                            //Unidade Tributável
            'qTrib' => '389.9500',                                      //Quantidade Tributável
            'vUnTrib' => '49.9200000000',                               //Valor Unitário de tributação
            'vFrete' => '',                                             //Valor Total do Frete
            'vSeg' => '',                                               //Valor Total do Seguro
            'vOutro' => '',                                             //Outras despesas acessórias
            'vDesc' => '',                                              //Valor do Desconto
            'indTot' => '1',                                            //Indica se valor do Item (vProd) entra no valor total da NF-e (vProd)
            'xPed' => '14972',                                          //Número do Pedido de Compra
            'nItemPed' => '1',                                          //Item do Pedido de Compra
            'nFCI' => ''),                                              //Número de controle da FCI - Ficha de Conteúdo de Importação
            'InfoImport' => array(
            'nDI' => '234556786',                                       //Número do Documento de Importação (DI, DSI, DIRE, ...)
            'dDI' => '22/12/2013',                                      //Data de Registro do documento
            'xLocDesemb' => 'SANTOS',                                   //Local de desembaraço
            'UFDesemb' => 'SP',                                         //Sigla da UF onde ocorreu o Desembaraço Aduaneiro
            'dDesemb' => '22/12/2013',                                  //Data do Desembaraço Aduaneiro
            'tpViaTransp' => '1',                                       //Via de transporte internacional informada na Declaração de Importação (DI)
            'vAFRMM' => '1.00',                                         //Valor da AFRMM - Adicional ao Frete para Renovação da Marinha Mercante
            'tpIntermedio' => '0',                                      //Forma de importação quanto a intermediação
            'CNPJ' => '',                                               //CNPJ do adquirente ou do encomendante
            'UFTerceiro' => '',                                         //Sigla da UF do adquirente ou do encomendante
            'cExportador' => '111',                                     //Código do Exportador
            'Adicoes' => array(
                'nAdicao' => '1',                                       //Numero da Adição
                'nSeqAdicC' => '1111',                                  //Numero sequencial do item dentro da Adição
                'cFabricante' => 'seila',                               //Código do fabricante estrangeiro
                'vDescDI' => '0.00',                                    //Valor do desconto do item da DI – Adição
                'nDraw' => '9393939')),                                 //Número do ato concessório de Drawback
        'DetExport' => array(
            'nDraw' => '',                                              //Número do ato concessório de Drawback
            'exportInd' => '',                                          //Grupo sobre exportação indireta
            'nRE' => '',                                                //Número do Registro de Exportação
            'chNFe' => '',                                              //Chave de Acesso da NF-e recebida para exportação
            'qExport' => ''),                                           //Quantidade do item realmente exportado
        'ProdEspec' => array(                                           //Apenas 1 dos itens ou nenhum - prever regras na entrada de dados e no tratamento de erros
            'tipo' => '',                                               //vazio - sem produto especifico; 0 - Veículos novos; 1 - medicamentos; 2 - arma; 3 - combustiveis
            'veicProd' => array(                                        //Detalhamento de Veículos novos
                'tpOp' => '',                                           //Tipo da operação
                'chassi' => '',                                         //Chassi do veículo
                'cCor' => '',                                           //Cor
                'xCor' => '',                                           //Descrição da Cor
                'pot' => '',                                            //Potência Motor (CV)
                'cilin' => '',                                          //Cilindradas
                'pesoL' => '',                                          //Peso Líquido
                'pesoB' => '',                                          //Peso Bruto
                'nSerie' => '',                                         //Serial (série)
                'tpComb' => '',                                         //Tipo de combustível
                'nMotor' => '',                                         //Número de Motor
                'CMT' => '',                                            //Capacidade Máxima de Tração
                'dist' => '',                                           //Distância entre eixos
                'anoMod' => '',                                         //Ano Modelo de Fabricação
                'anoFab' => '',                                         //Ano de Fabricação
                'tpPint' => '',                                         //Tipo de Pintura
                'tpVeic' => '',                                         //Tipo de Veículo
                'espVeic' => '',                                        //Espécie de Veículo
                'VIN' => '',                                            //Condição do VIN
                'condVeic' => '',                                       //Condição do Veículo
                'cMod' => '',                                           //Código Marca Modelo
                'cCorDENATRAN' => '',                                   //Código da Cor
                'lota' => '',                                           //Capacidade máxima de lotação
                'tpRest' => ''),                                        //Restrição
            'med' => array(                                             //Detalhamento de Medicamentos e de matérias-primas farmacêuticas
                'nLote' => '',                                          //Número do Lote de medicamentos ou de matérias-primas farmacêuticas
                'qLote' => '',                                          //Quantidade de produto no Lote de medicamentos ou de matérias-primas farmacêuticas
                'dFab' => '',                                           //Data de fabricação
                'dVal' => '',                                           //Data de validade
                'vPMC' => ''),                                          //Preço máximo consumidor
            'arma' => array(                                            //Detalhamento de Armamento
                'tpArma' => '',                                         //Indicador do tipo de arma de fogo
                'nSerie' => '',                                         //Número de série da arma
                'nCano' => '',                                          //Número de série do cano
                'descr' => ''),                                         //Descrição completa da arma, compreendendo: calibre, marca, capacidade, tipo de funcionamento, comprimento e demais elementos que permitam a sua perfeita identificação.
            'comb' => array(                                            //Informações específicas para combustíveis líquidos e lubrificantes
                'cProdANP' => '',                                       //Código de produto da ANP
                'pMixGN' => '',                                         //Percentual de Gás Natural para o produto GLP (cProdANP=210203001)
                'CODIF' => '',                                          //Código de autorização / registro do CODIF
                'qTemp' => '',                                          //Quantidade de combustível faturada à temperatura ambiente.
                'UFCons' => '',                                         //Sigla da UF de consumo
                'qBCProd' => '',                                        //BC da CIDE
                'vAliqProd' => '',                                      //Valor da alíquota da CIDE
                'vCIDE' => ''),                                         //Valor da CIDE
            'nRECOPI' => ''),                                           //Número do RECOPI
        'Imposto' => array(                                             //Grupo ISSQN mutuamente exclusivo com os grupos ICMS e II, isto é, se o grupo ISSQN for informado os grupos ICMS e II não serão informados e vice-versa.
            'vTotTrib' => '',                                           //Valor aproximado total de tributos federais, estaduais e municipais.
            'ICMS' => array(                                            //A diferenca entre os ICMS serao identificadas pelo campo cst
                'tipo' => '0',                                           //0 - normal; 1 - Partilha; 2 - Subst Tributaria; 3 - Simples
                'orig' => '1',                                          //Origem da mercadoria
                'CST' => '00',                                          //Tributação do ICMS: o que vai estabelecer a diferenca entre os ICMS
                'modBC' => '3',                                         //Modalidade de determinação da BC do ICMS
                'pRedBC' => '',                                         //Percentual da Redução de BC
                'vBC' => '19466.30',                                    //Valor da BC do ICMS
                'pICMS' => '12.00',                                     //Alíquota do imposto
                'vICMS' => '2335.96',                                   //Valor do ICMS
                'vICMSDeson' => '',                                     //Valor do ICMS desonerado
                'motDesICMS' => '',                                     //Motivo da desoneração do ICMS
                'modBCST' => '',                                        //Modalidade de determinação da BC do ICMS ST
                'pMVAST' => '',                                         //Percentual da margem de valor Adicionado do ICMS ST
                'pRedBCST' => '',                                       //Percentual da Redução de BC do ICMS ST
                'vBCST' => '',                                          //Valor da BC do ICMS ST
                'pICMSST' => '',                                        //Alíquota do imposto do ICMS ST
                'vICMSST' => '',                                        //Valor do ICMS ST
                'pDif' => '',                                           //Percentual do diferimento
                'vICMSDif' => '',                                       //Valor do ICMS diferido
                'vICMSOp' => '',                                        //Valor do ICMS da Operação
                'vBCSTRet' => '',                                       //Valor da BC do ICMS ST retido
                'vICMSSTRet' => '',                                     //Valor do ICMS ST retido
                'pBCOp' => '',                                          //Percentual da BC operação própria
                'UFST' => '',                                           //UF para qual é devido o ICMS ST
                'CSOSN' => '',                                          //Código de Situação da Operação – Simples Nacional
                'pCredSN' => '',                                        //Alíquota aplicável de cálculo do crédito (Simples Nacional).
                'vCredICMSSN' => ''),                                   //Valor crédito do ICMS que pode ser aproveitado nos termos do art. 23 da LC 123 (Simples Nacional)
            'IPI' => array(                                             //Informar apenas quando o item for sujeito ao IPI
                'CST' => '55',                                          //Código da situação tributária do IPI
                'clEnq' => '',                                          //Classe de enquadramento do IPI para Cigarros e Bebidas
                'cnpjProd' => '',                                       //CNPJ do produtor da mercadoria, quando diferente do emitente. Somente para os casos de exportação direta ou indireta.
                'cSelo' => '',                                          //Código do selo de controle IPI
                'qSelo' => '',                                          //Quantidade de selo de controle
                'cEnq' => '999',                                        //Código de Enquadramento Legal do IPI
                'vBC' => '',                                            //Valor da BC do IPI
                'pIPI' => '',                                           //Alíquota do IPI
                'qUnid' => '',                                          //Quantidade total na unidade padrão para tributação (somente para os produtos tributados por unidade)
                'vUnid' => '',                                          //Valor por Unidade Tributável
                'vIPI' => ''),                                          //Valor do IPI
            'PIS' => array(
                'tipo' => '0',                                          //0 - PIS normal; 1 - PISST
                'CST' => '01',                                          //Código de Situação Tributária do PIS
                'vBC' => '19466.30',                                    //Valor da Base de Cálculo do PIS
                'pPIS' => '1.65',                                       //Alíquota do PIS (em percentual)
                'vPIS' => '321.19',                                     //Valor do PIS
                'qBCProd' => '',                                        //Quantidade Vendida
                'vAliqProd' => ''),                                     //Alíquota do PIS (em reais)
            'COFINS' => array(
                'tipo' => '0',                                          //0 - CONFINS; 1 - COFINSST
                'CST' => '01',                                          //Código de Situação Tributária da COFINS
                'vBC' => '19466.30',                                    //Valor da Base de Cálculo da COFINS
                'pCOFINS' => '7.60',                                    //Alíquota da COFINS (em percentual)
                'vCOFINS' => '1479.44',                                 //Valor da COFINS
                'qBCProd' => '',                                        //Quantidade Vendida
                'vAliqProd' => ''),                                     //Alíquota da COFINS (em reais)
            'II' => array(
                'vBC' => '',                                            //Valor BC do Imposto de Importação
                'vDespAdu' => '',                                       //Valor despesas aduaneiras
                'vII' => '',                                            //Valor Imposto de Importação
                'vIOF' => ''),                                          //Valor Imposto sobre Operações Financeiras
            'ISSQN' => array(                                           //todo:excludente com relação ao ICMS, PIS, CONFINS, etc. Tratar entrada de dados e erros
                'vBC' => '',                                            //Valor da Base de Cálculo do ISSQN
                'vAliq' => '',                                          //Alíquota do ISSQN
                'vISSQN' => '',                                         //Valor do ISSQN
                'cMunFG' => '',                                         //Código do município de ocorrência do fato gerador do ISSQN
                'cListServ' => '',                                      //Item da Lista de Serviços
                'vDeducao' => '',                                       //Valor dedução para redução da Base de cálculo
                'vOutro' => '',                                         //Valor outras retenções
                'vDescIncond' => '',                                    //Valor desconto incondicionado
                'vDescCond' => '',                                      //Valor desconto condicionado
                'vISSRet' => '',                                        //Valor retenção ISS
                'indISS' => '',                                         //Indicador da exigibilidade do ISS
                'cServico' => '',                                       //Código do serviço prestado dentro do município
                'cMun' => '',                                           //Código do Município de incidência do imposto
                'cPais' => '',                                          //Código do País onde o serviço foi prestado
                'nProcesso' => '',                                      //Número do processo judicial ou administrativo de suspensão da exigibilidade
                'indIncentivo' => '')),                                    //Indicador de incentivo Fiscal
        'TributosDevolvidos' => array(
            'pDevol' => '',                                             //Percentual da mercadoria devolvida
            'vIPIDevol' => ''),                                         //Valor do IPI devolvido
        'infAdProd' => '')),                                             //Norma referenciada, informações complementares, etc.
    'Totais' => array(
        'ICMSTot' => array(
            'vBC' => '19466.30',                                        //Base de Cálculo do ICMS
            'vICMS' => '2335.96',                                       //Valor Total do ICMS
            'vICMSDeson' => '0.00',                                     //Valor Total do ICMS desonerado
            'vBCST' => '0.00',                                          //Base de Cálculo do ICMS ST
            'vST' => '0.00',                                            //Valor Total do ICMS ST
            'vProd' => '19466.30',                                      //Valor Total dos produtos e serviços
            'vFrete' => '0.00',                                         //Valor Total do Frete
            'vSeg' => '0.00',                                           //Valor Total do Seguro
            'vDesc' => '0.00',                                          //Valor Total do Desconto
            'vII' => '0.00',                                            //Valor Total do II
            'vIPI' => '0.00',                                           //Valor Total do IPI
            'vPIS' => '321.19',                                         //Valor do PIS
            'vCOFINS' => '1479.44',                                     //Valor da COFINS
            'vOutro' => '0.00',                                         //Outras Despesas acessórias
            'vNF' => '19466.30',                                        //Valor Total da NF-e
            'vTotTrib' => ''),                                          //Valor aproximado total de tributos federais, estaduais e municipais.
        'ISSQNtot' => array(
            'vServ' => '',                                              //Valor total dos Serviços sob não-incidência ou não tributados pelo ICMS
            'vBC' => '',                                                //Valor total Base de Cálculo do ISS
            'vISS' => '',                                               //Valor total do ISS
            'vPIS' => '',                                               //Valor total do PIS sobre serviços
            'vCOFINS' => '',                                            //Valor total da COFINS sobre serviços
            'dCompet' => '',                                            //Data da prestação do serviço
            'vDeducao' => '',                                           //Valor total dedução para redução da Base de Cálculo
            'vOutro' => '',                                             //Valor total outras retenções
            'vDescIncond' => '',                                        //Valor total desconto incondicionado
            'vDescCond' => '',                                          //Valor total desconto condicionado
            'vISSRet' => '',                                            //Valor total retenção ISS
            'cRegTrib' => ''),                                          //Código do Regime Especial de Tributação
        'retTrib' => array(
            'vRetPIS' => '',                                            //Valor Retido de PIS
            'vRetCOFINS' => '',                                         //Valor Retido de COFINS
            'vRetCSLL' => '',                                           //Valor Retido de CSLL
            'vBCIRRF' => '',                                            //Base de Cálculo do IRRF
            'vIRRF' => '',                                              //Valor Retido do IRRF
            'vBCRetPrev' => '',                                         //Base de Cálculo da Retenção da Previdência Social
            'vRetPrev' => '')),                                         //Valor da Retenção da Previdência Social
    'Transporte' => array(
        'modFrete' => '0',                                              //Modalidade do frete
        'transporta' => array(
            'CNPJ' => '',                                               //CNPJ do Transportador
            'CPF' => '12345678901',                                     //CPF do Transportador
            'xNome' => 'Ze da Carroca',                                 //Razão Social ou nome
            'IE' => '',                                                 //Inscrição Estadual do Transportador
            'xEnder' => 'Beco Escuro',                                  //Endereço Completo
            'xMun' => 'Campinas',                                       //Nome do município
            'UF' => 'SP'),                                              //Sigla da UF
        'retTransp' => array(                                           //Grupo Retenção ICMS transporte
            'vServ' => '258,69',                                        //Valor do Serviço
            'vBCRet' => '258,69',                                       //BC da Retenção do ICMS
            'pICMSRet' => '10,00',                                      //Alíquota da Retenção
            'vICMSRet' => '25,87',                                      //Valor do ICMS Retido
            'CFOP' => '5352',                                           //CFOP de Serviço de Transporte (Anexo XIII.03).
            'cMunFG' => '3509502'),                                     //Código do município de ocorrência do fato gerador do ICMS do transporte
        'veicTransp' => array(                                          //Grupo Veículo Transporte
            'placa' => 'AAA1212',                                       //Placa do Veículo
            'UF' => 'SP',                                               //Sigla da UF
            'RNTC' => '12345678'),                                      //Registro Nacional de Transportador de Carga (ANTT)
        'reboque' => array(
            array(
                'placa' => '',                                          //Placa do Veículo
                'UF' => '',                                             //Sigla da UF
                'RNTC' => '',                                           //Registro Nacional de Transportador de Carga (ANTT)
                'vagao' => '',                                          //Identificação do vagão
                'balsa' => '')),                                        //Identificação da balsa
        'vol' => array(
            array(
                'qVol' => '24',                                         //Quantidade de volumes transportados
                'esp' => 'VOLUMES',                                     //Espécie dos volumes transportados
                'marca' => '',                                          //Marca dos volumes transportados
                'nVol' => '',                                           //Numeração dos volumes transportados
                'pesoL' => '389.950',                                   //Peso Líquido (em kg)
                'pesoB' => '399.550',                                   //Peso Bruto (em kg)
                'aLacres' => array(                                     //Grupo Lacres
                    'nLacre' => '')))),                                 //Número dos Lacres
    'Cobranca' => array(
        'fat' => array(                                                 //Grupo Fatura
            'nFat' => '000034189',                                      //Número da Fatura
            'vOrig' => '19466.30',                                      //Valor Original da Fatura
            'vDesc' => '',                                              //Valor do desconto
            'vLiq' => '19466.30'),                                      //Valor Líquido da Fatura
        'dup' => array(                                                 //Grupo Duplicata
            array(
                'nDup' => '',                                           //Número da Duplicata
                'dVenc' => '',                                          //Data de vencimento
                'vDup' => ''))),                                        //Valor da duplicata
    'FormaPagamento' => array(                                          //Grupo obrigatório para a NFC-e, a critério da UF. Não informar para a NF-e.
        'tPag' => '',                                                   //Forma de pagamento
        'vPag' => '',                                                   //Valor do Pagamento
        'card' => array(                                                //Grupo de Cartões
            'CNPJ' => '31551765000143',                                 //CNPJ da Credenciadora de cartão de crédito e/ou débito
            'tBand' => '01',                                            //Bandeira da operadora de cartão de crédito e/ou débito
            'cAut' => 'AB254FC79001')),                                 //Número de autorização da operação cartão de crédito e/ou débito
    'InfoAdic' => array(
        'infAdFisco' => 'SAIDA C/ SUSP IPI CONF ART 29 DA LEI 10.637',  //Informações Adicionais de Interesse do Fisco
        'infCpl' => '',                                                 //Informações Complementares de interesse do Contribuinte
        'ObsEmitente' => array(                                         //Grupo Campo de uso livre do contribuinte
            array(
                'xCampo' => '',                                         //Identificação do campo
                'xTexto' => '')),                                       //Conteúdo do campo
        'ObsFisco' => array(                                            //Grupo Campo de uso livre do Fisco
            array(
                'xCampo' => '',                                         //Identificação do campo
                'xTexto' => '')),                                       //Conteúdo do campo
        'Processos' => array(                                           //Grupo Processo referenciado
            array(
                'nProc' => '',                                          //Identificador do processo ou ato concessório
                'indProc' => ''))),                                     //Indicador da origem do processo
    'Exporta' => array(
        'UFSaidaPais' => 'SP',                                          //Sigla da UF de Embarque ou de transposição de fronteira
        'xLocExporta' => 'Maritimo',                                    //Descrição do Local de Embarque ou de transposição de fronteira
        'xLocDespacho' => 'Porto Santos'),                              //Descrição do Local de Embarque ou de transposição de fronteira
    'Compra' => array(
        'xNEmp' => '',                                                  //Nota de Empenho
        'xPed' => '12345',                                              //Pedido
        'xCont' => 'A342212'),                                          //Contrato
    'Cana' => array(
        'safra' => '2014',                                              //Identificação da safra
        'ref' => '01/2014',                                             //Mês e ano de referência
        'forDia' => array(                                              //Grupo Fornecimento diário de cana
            array(
                'dia' => '',                                            //Dia
                'qtde' => '',                                           //Quantidade
                'qTotMes' => '',                                        //Quantidade Total do Mês
                'qTotAnt' => '',                                        //Quantidade Total Anterior
                'qTotGer' => '')),                                      //Quantidade Total Geral
        'deduc' => array(                                               //Grupo Deduções – Taxas e Contribuições
            'xDed' => '',                                               //Descrição da Dedução
            'vDed' => '',                                               //Valor da Dedução
            'vFor' => '',                                               //Valor dos Fornecimentos
            'vTotDed' => '',                                            //Valor Total da Dedução
            'vLiqFor' => '')                                            //Valor Líquido dos Fornecimentos
    )


);

//Chamada da classe

$nfe = new DsNFe($nfeDados);

header('Content-type: text/xml; charset=UTF-8');
echo $nfe->processaNFe();




/* Só para eu ter a lista de arrays do primeiro nível
foreach($nfeDados as $k => $v){
    echo '$'.$k.' = $this->dNFe[\''.$k.'\'];';
    echo '<br>';
}
*/